version: '3'
services:
  app:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: sila_fastapi_task
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
